### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by Gab-Metzger-Melpia** [Arnaud73/ngx-matomo#1]
Hello Arnaud,

Thanks for your awesome matomo wrapper.
I'm trying to use it but I have a small error when the matomo code is injected.

I'm getting `GET https://analytics.changr.com/piwik.js 0 ()`

I used the injector as following:
`this.matomoInjector.init('https://analytics.changr.com/', environment.MATOMO_SITE_ID);`

Do you have any idea of the origin of my issue?

Thanks a lot,
Gabriel

**Comment by Gab-Metzger-Melpia** [comment]
Nevermind, this issue was raised because of my adblocker. Good to know :)

**Comment by Arnaud73** [comment]
No problem :)

FYI, beware also of DNT (by default, Matomo drops all calls when DNT is set to true).

**Comment by Gab-Metzger-Melpia** [comment]
Yes I saw that, thanks!
