### ISSUE TITLE
Not compatible with Angular 16

### ISSUE THREAD

**Issue by fpd007** [Arnaud73/ngx-matomo#101]
ngx-matomo depends on @angular/common@>=14.0.0 **<16.0.0** which results in an error when installing an Angular 16 project that uses ngx-matomo 1.10

**Comment by tarlepp** [comment]
I'm having same issue.

**Comment by christian-tigges** [comment]
I also have the same issue.
Is there an update planned?

**Comment by Arnaud73** [comment]
The library is currently not compatible with Angular 16, I will migrate to code to Angular 16 in the next few days.
Sorry for the inconvenience

**Comment by Arnaud73** [comment]
ngx-matomo 2.0.0-rc.0 is available for testing with complete support for Angular 16!
Please let me know if you encounter any issue with it!

**Comment by tarlepp** [comment]
I can confirm that `2.0.0-rc.1` version works with Angular `16.x`

**Comment by Arnaud73** [comment]
Thanks @tarlepp :)
If no one raises any concern before early next week, I'll release 2.0.0 :)

**Comment by Arnaud73** [comment]
Version 2.0.0 is now published!

**Comment by christian-tigges** [comment]
I can also confirm, that it works fine now with latest Angular 16 version. 
Thanks a lot. :)
