### ISSUE TITLE
UserId

### ISSUE THREAD

**Issue by ambroiseRabier** [Arnaud73/ngx-matomo#18]
There is this line `this.matomoTracker.setUserId('UserId');`, is the string UserId supposed to be replaced by your own userId ? What are the recommendation for that, and hash stored on localStorage ?

**Comment by Arnaud73** [comment]
Hello,

Yes, `UserId` is left up to you. It is used to track the id of the user connected to your application.

Check https://matomo.org/docs/user-id/ for more information about how Matomo handles it. ngx-matomo provides a simple wrapper around the Matomo function.
