### ISSUE TITLE
npm warn for angular > 6.0.0

### ISSUE THREAD

**Issue by agims7** [Arnaud73/ngx-matomo#2]
H Arnaud,

We recently updated our project to the newest version and during installation we are getting npm warn:

```npm WARN ngx-matomo@0.1.0 requires a peer of @angular/core@>=5.0.0 <6.0.0 but none is installed. You must install peer dependencies yourself```

Our angular version is -> ```"@angular/core": "6.0.7"```

Is it possible to fix thix warning?

**Comment by Arnaud73** [comment]
Hi Michal,

I know this issue (my project has been migrated some time ago to Angular 6). I'm going to fix it is August (I want to test how Angular CLI 6 handles library projects).

In the meantime, this is just a warning, but the library as it is built is fully compatible with Angular 6.

**Comment by Arnaud73** [comment]
Now fixed in 0.1.1 :) :)

**Comment by agims7** [comment]
Perfect :) but there is one problem npm is still now up to date or it has some cache..

When trying to install latest version there is still 0.1.0 and when manually changing to 0.1.1 there is warning that version not found.

![zaznaczenie_017](https://user-images.githubusercontent.com/18736434/43625918-d191339e-96ef-11e8-95b8-00d1035290c2.jpg)
