### ISSUE TITLE
removeEcommerceItem does not exist

### ISSUE THREAD

**Issue by thesignal** [Arnaud73/ngx-matomo#25]
Hi,

it seems that the `removeEcommerceItem` function is not implemented. Could you add it? 

Or is there a reason why it's not implemented? (`addEcommerceItem` and `trackEcommerceCartUpdate` are there)

Regards,

Philipp

**Comment by Arnaud73** [comment]
Hi,

I got the list of function from a page that should have listed all the functions of the tracker. However, I already discovered some that were missing. You managed to add one to the list.

I'm going to implement this function as well.

Thanks for notifying it!

Arnaud

**Comment by Arnaud73** [comment]
Also, functions `clearEcommerceCart` and `getEcommerceItems` were also missing. They shall be included as well in a later release.

**Comment by thesignal** [comment]
Great, thanks!
