### ISSUE TITLE
v0.1.4 : make a new tag to allow SSR fix

### ISSUE THREAD

**Issue by MaitreDede** [Arnaud73/ngx-matomo#32]
Hi,
I am using your library at v0.1.4, the latest tag at time of writing.
It is possible to release a new tag so the SSR fix would be available ?
Thanks :)

**Comment by Arnaud73** [comment]
Sorry for the late answer.

SSR fix is available in https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0.

You can test this version right now, it shall be better than version 0.1.4.

Version 1.0 will be full released when Angular 12 is live (which shall happen this month).
