### ISSUE TITLE
Support of Angular 9

### ISSUE THREAD

**Issue by fgubler** [Arnaud73/ngx-matomo#33]
Angular 9 has some very nice new features such as the new Ivy compiler reducing app-size and also support for newer versions of TypeScript.

It would be awesome if ngx-matomo would support the new version.

**Comment by Arnaud73** [comment]
Version 1.0 that will reach RC in the next few days is targeted for Angular 9 first.

Stay tuned :)

**Comment by fgubler** [comment]
That is great news! Thanks a lot.

**Comment by cahergil** [comment]
I am using this package for Matomo and Angular 9, and it seems to be working ok, except to the tracking of events that are not shown in the **Behaviour->Events** section, may it be related to this package not being yet updated to Angular 9? Thanks in advance!

**Comment by wmadev** [comment]
> Version 1.0 that will reach RC in the next few days is targeted for Angular 9 first.
> 
> Stay tuned :)

Any news on the release date of a version supporting Angular 9?
