### ISSUE TITLE
Doesn't work for Angular 10

### ISSUE THREAD

**Issue by sergiotome** [Arnaud73/ngx-matomo#44]
Even though the readme says that this works with Angular 5, 6, 7 and 8, I managed to install it on an angular 9 app with no problems.  Now that Angular 10 is out there, is there any plan to make it compatible with Angular 10?

**Comment by sergiotome** [comment]
By the way, this is what I get when I try to upgrade an app from Angular 9 to 10

![image](https://user-images.githubusercontent.com/16870246/87681034-6c991580-c77e-11ea-8b7b-52044aaf944b.png)

**Comment by xaviergxf** [comment]
any news about this? I have only a warning when doing a npm install:

npm WARN ngx-matomo@0.1.4 requires a peer of @angular/core@>=5.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by Javarome** [comment]
Seems to work if your `--force` it.

**Comment by sbley** [comment]
@Arnaud73 Could you consider publishing a compatibility update for Angular 10 prior to releasing 1.0?

**Comment by tehZeno** [comment]
@electrofly maybe you can publish it? since your PR seems to not get reviewed?

**Comment by tehZeno** [comment]
there is a v9 published @ https://www.npmjs.com/package/ngx-matomo-v9

**Comment by electrofLy** [comment]
@tehZeno I don't really plan to support it so I don't think it would be worth publishing it myself

**Comment by sbley** [comment]
Looks like this repository is not maintained anymore. Does anyone have contact to the repo owners so we can discuss how to keep development going?

**Comment by EmmanuelRoux** [comment]
Hi @sergiotome, @sbley

Since this repository seems not to be maintained anymore, I decided to create from scratch a new plugin compatible with Angular 11 : https://github.com/EmmanuelRoux/ngx-matomo

I know there are many forks based on this project, but I did choose to create a new plugin from scratch, as there are some bugs and I decided to go for a completely new project structure.

Feel free to try it and give me some feedbacks!

**Comment by Arnaud73** [comment]
Sorry for the very long delay, I wasn't able to dedicate any time on this project this last few months.

Good news : release 1.0 was almost ready for quite some time, so I finished it and released yesterday an RC.0 : https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0.

This one contains all fixes that were ready to be delivered plus all the planned major features.

Version 1.0.0 will be officially released just after Angular 12 is live, which shall occur this month.

**Comment by Arnaud73** [comment]
Sorry for the very long delay, I wasn't able to dedicate any time on this project this last few months.
G, release 1.0 was almost ready for quite some time, so I finished it and released yesterday an RC.0 : https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0.

This one contains all fixes that were ready to be delivered plus all the planned major features.

Version 1.0.0 will be officially released just after Angular 12 is live.

**Comment by blalasaadri** [comment]
@Arnaud73 Since Angular 12 has been released now, can we expect the release of version 1.0.0 soon? From what I can see, RC.1 is the latest release right now.

**Comment by Arnaud73** [comment]
Hi @blalasaadri , release 1.0 is almost there. I understood why I could not make the release built with Angular 12 work with Angular 9-11 apps. I still have some minors modifications to finish and check one last bug posted this morning. Release 1.0 is I hope just a few days away.
