### ISSUE TITLE
Support for multiple tracker instances / addTracker

### ISSUE THREAD

**Issue by Turom** [Arnaud73/ngx-matomo#45]
Greetings,

The library doesn't seem to support the `addTracker` command and a way to handle multiple trackers from different servers.

See https://developer.matomo.org/guides/tracking-javascript-guide#multiple-piwik-trackers

Is there a way to handle this and create multiple tracker instances with the current implementation?

Cheers

**Comment by Arnaud73** [comment]
Hi @Turom Turom,

This feature is already developed and will be in the new release of the library (1.0) that will update the way the tracker is loaded and initialized.

This implementation will enable you to declare multiple trackers when loading the module. However, I did not consider that people would like to add additional trackers later on. Would that cover your need?
