### ISSUE TITLE
All requests to piwik/matomo are blocked by ad blockers

### ISSUE THREAD

**Issue by suppadeliux** [Arnaud73/ngx-matomo#46]
Trying to implement this in my angular application, but I was only able to do it after disabling my ad blocker.

I am using ublock.

Does any body know how to track the visit without having to disable ad blockers?

I saw some threads about this, in the matomo repo, but nothing helped me since I am using ngx-matomo.

thanks

**Comment by egesu** [comment]
Maybe using same top-level domain for matomo and your website? But this is not an issue about this package.

**Comment by sbley** [comment]
There is a German post about this here: https://christianmochow.de/beitraege/tools/catch-me-if-you-can-adblocker-umgehen-mit-matomo/
But as said before, this is not an issue of ngx-matomo.

**Comment by Arnaud73** [comment]
Sorry for the late answer, but I agree with the previous replies : there is no way from the application or any used library to prevent ad-blockers from doing their job.
If you are using an ad-blocker, make sure it is deactivated on the development site you are working on.
