### ISSUE TITLE
Is this repo still maintained ?

### ISSUE THREAD

**Issue by ArnaudPel** [Arnaud73/ngx-matomo#50]
I am considering Matomo to monitor our Angular (11) app. This repository is the reference provided on their [integration page](https://matomo.org/integrate/).

Yet I seem to notice that:
- the last commit on master is 1+ year old
- the last commit on develop is 7+ months old
- the last merged PR is more than a year old (11 PR opened, most of them without reply)
- it is not clear whether milestone [Release 1](https://github.com/Arnaud73/ngx-matomo/milestone/1) will see any further progress

I understand that the maintainer may no longer be able to contribute to this project for free. But in that case, at least the readme should be updated with a clear mention at the top, indicating that contributors shouldn't waste their time.

Thanks

**Comment by dippa-1** [comment]
Have you found an alternative for Angular 11?

**Comment by ArnaudPel** [comment]
Sorry I never got round to actually integrating Matomo. My manager never replied to my questions about deploying Matomo on premises, and since then I have left that company.

If you have the means to do it, I could suggest forking this repository, and making the necessary changes to support Angular 11 yourself.

**Comment by evoytenkoapps** [comment]
what about 21 day free trial account? is it enough ?

**Comment by EmmanuelRoux** [comment]
Hi @ArnaudPel, @evoytenkoapps

Since this repository seems not to be maintained anymore, I decided to create from scratch a new plugin compatible with Angular 11 : https://github.com/EmmanuelRoux/ngx-matomo

I know there are many forks based on this project, but I did choose to create a new plugin from scratch, as there are some bugs and I decided to go for a completely new project structure.

Feel free to test it and give me some feedbacks!

**Comment by Arnaud73** [comment]
Sorry for the very long delay, I wasn't able to dedicate any time on this project this last few months.

The repo is not dead, release 1.0 was almost ready for quite some time, so I finished it and released yesterday an RC.0 : https://www.npmjs.com/package/ngx-matomo/v/1.0.0-rc.0.

This one contains all fixes that were ready to be delivered plus all the planned major features.

Version 1.0.0 will be officially released just after Angular 12 is live.
