### ISSUE TITLE
Not updated on npmjs?

### ISSUE THREAD

**Issue by JaapBarnhoorn** [Arnaud73/ngx-matomo#64]
Hi @Arnaud73, I just tried to install the package and it resolves to a 0.2.0 version by eduardmarcinco.
Maybe it's my local acting up but could you perhaps double check it's updated on npmjs properly?
https://www.npmjs.com/package/ngx-matomo

EDIT: nvm doing npm install --save ngx-matomo@v1.0.0-rc.1 fixes my problem.. not aware it was still an rc

**Comment by Arnaud73** [comment]
Hi,
Sorry for the long delay.
ngx-Matomo has now been updated on NPMjs and released as 1.0 with a few modifications.
