### ISSUE TITLE
 Update project dependencies to angular 13, if this is not possible we will no longer use your package

### ISSUE THREAD

**Issue by ambarkiy** [Arnaud73/ngx-matomo#79]
Update project dependencies to angular 13, if this is not possible we will no longer use your package

**Comment by devzfactor** [comment]
@ambarkiy I updated matomo to angular version 13 (we also needed this package for angular 13, and then updated, if @Arnaud73  also updates this package after this, you can switch back) 
here ngx-z-matomo
https://www.npmjs.com/package/ngx-z-matomo

**Comment by Arnaud73** [comment]
Hi,
The package has been finally published as 1.0 with Angular 14 support.
If your application still relies on Angular 13, I suggest you stick with ngx-z-matomo which shall be perfectly fine.

**Comment by nopapername** [comment]
> @ambarkiy I updated matomo to angular version 13 (we also needed this package for angular 13, and then updated, if @Arnaud73 also updates this package after this, you can switch back) here ngx-z-matomo https://www.npmjs.com/package/ngx-z-matomo

It seems that you recently updated the 1.0.11 version of ngx-z-matomo to support ng15, and the corresponding version 1.0.7 supported by angular13, so you need to change it in the package.json file to `"ngx-z-matomo": " =1.0.7"`
