### ISSUE TITLE
Update to Angular 7

### ISSUE THREAD

**Issue by mjehle82** [Arnaud73/ngx-matomo#9]
Can you please update the project to Angular Version 7?
I've tried with a pull request but am obviously getting some errors in the build pipeline that I am unable to resolve...
An update would be greatly appreciated!
Cheers, Mike

**Comment by agims7** [comment]
+1 current version suppoer only 7.0.0 version of angular
`"peerDependencies": {
        "@angular/core": ">=5.0.0 <7.0.0"
    },`

please update it

**Comment by micheladennis** [comment]
Have the same issue

**Comment by Arnaud73** [comment]
Latest releases of ngx-matomo support all Angular 7 releases. Please check that you are using an up to date version.
